//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjDBHomework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbHomeworkEntities8 : DbContext
    {
        public dbHomeworkEntities8()
            : base("name=dbHomeworkEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Art> Art { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Collects> Collects { get; set; }
        public virtual DbSet<Gallery> Gallery { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Visits> Visits { get; set; }
    }
}
